# Generated by Django 5.0.4 on 2024-05-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=300, verbose_name='City')),
                ('timezone', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='location',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
